[ExportVerilog] Inline _T wires
llvm/circt pull request #2755
Opened 2022-03-12 01:58 UTC by sinofp

Now the example in #2674 will produce the following with `--disable-name-preservation`:

```verilog
module Foo(     // .\2674.fir:2:10
  input  a, b, c, d,
  output e, f);

  assign e = a | b | c | d;     // .\2674.fir:2:10, :10:17, :12:14
  assign f = a | b | c & d;     // .\2674.fir:2:10, :10:17, :14:19, :15:14
endmodule
```

The judgment relies on the original name of the CSE’d expression. I don’t know whether it is sufficient.

2022-03-15 19:03 UTC, darthscsi requested changes
Export Verilog should have no Chisel specific hooks or hacks.  Namehints that don't matter, like _T should be removed earlier in the pipeline.  We use to systematically strip out _T names, did something change?

2022-03-15 22:11 UTC, sinofp commented
I’m happy to change, but I don’t know the criteria to identify a temporary signal. Can you give me some hints?

I used to consider `hw::Combinational`. This code works fine for the example, but I think it will inline other non-temporary signals. So, in the end, I used name hints.

2022-03-16 11:47 UTC, uenoku commented
I guess the original issue is a bit different. I understand the goal of the issue is "inline (CSEd) expressions more aggressively if they are cheap to inline", like `a | b`. One way to implement this would be to extend `isDuplicatableExpression` in ExportVerilog 
to return `true` for small expressions whose operands are emitted as symbols (e.g. arguments, wires, regs..).

2022-03-16 12:22 UTC, sinofp commented
I missed the “if they are cheap to inline” part of the original issue, so I think I need to detect all those temporaries. Inline only those expressions composed by arguments/wires/regs sounds reasonable, thank you.

2022-03-17 01:08 UTC, sinofp commented
1f74f43 inlines AndOp/OrOp/XorOp composed by BlockArgument/RegOp/WireOp/ConstantOp/LocalParamOp/ParamValueOp.

2022-03-23 20:32 UTC, darthscsi commented on lib/Conversion/ExportVerilog/ExportVerilog.cpp
> +  if (isa<AndOp, OrOp, XorOp>(op)) {
We have some constraints which can't be solved here easily.  always event lists must not be expressions (often).  When they are not expressions, if inside them must use the same wire and not inline the expression.

The solution we are moving to is for export verilog to always inline and these kinds of choices are made in prepare.

2023-02-28 05:46 UTC, darthscsi commented
I think this is subsumed by later work on naming.  Closing.

2023-02-28 05:46 UTC, closed without merging