[FIRRTL] Simplify NonLocalAnchor namepath printing
llvm/circt pull request #3179
Opened 2022-05-24 06:51 UTC by youngar

Printing the namepath array as a regular attribute means we have a lot
of  overhead to write out all the `hw.innerRefAttr`s.  This changes the
NLA operation printer to print the namepath array without the name of
the of the attributes.

```mlir
// Before:
firrtl.nla @nla_1 [#hw.innerNameRef<@Foo::@bar>, #hw.innerNameRef<@Bar::@b>]
// After:
firrtl.nla @nla_1 [@Foo::@bar, @Bar::@b]
```

If anyone has any other suggestions for the printed format, I would love to bike-shed on this. We could choose something similar to the annotation target strings: `Foo/bar:Bar/b`

2022-05-24 07:02 UTC, youngar commented on lib/Dialect/FIRRTL/FIRRTLOps.cpp
> +                                      "only one nested reference is allowed");
forgot to add a test for this

2022-05-24 15:18 UTC, dtzSiFive requested changes
Thank you, this is much nicer!!
I might actually write an NLA by hand now :laughing: .

Tests I scanned through, LGTM since they pass :smile:.

Parsing/printing LGTM but I'm not an expert on the footguns there.

The touched docs are already dated (and "wrong" for current CIRCT), the only portion I'm asking to be fixed in this PR are the minor typo/name fixups in the examples (let's not make it more wrong :+1:).

Thanks again for tackling this! :rocket:

2022-05-24 17:37 UTC, dtzSiFive commented
> Lots of problems in the docs, thanks @dtzSiFive for pointing it out. I ran the example through `circt-opt` so that I know it compiles. I deleted the illegal 1-element NLA, the `sv.verbatim` that was never supported, and the entire second example. I swapped some module names around so the hierarchy is `Foo -> Bar -> Baz`. Changed a whole bunch of the wording in the paragraph. The textual description of what the namepath is is not perfect but I hope it's at least accurate.

Awesome, thank you!! I was using `firtool`, oops.  `circt-opt` things are good now, :+1:!.

2022-05-24 17:39 UTC, dtzSiFive approved these changes
Thanks for addressing my comments, LGTM now.

2022-05-24 22:31 UTC, youngar commented
@darthscsi how do you feel about this?  I think there are probably lots of places where the default attribute printers are too verbose in the textual IR format and a custom op printer can pave over the lack of flexibility in the attribute printer. (e.g. we can probably reuse this while printing the symbol list of the `sv.verbatim` op)

2022-05-25 20:32 UTC, darthscsi commented
> @darthscsi how do you feel about this? I think there are probably lots of places where the default attribute printers are too verbose in the textual IR format and a custom op printer can pave over the lack of flexibility in the attribute printer. (e.g. we can probably reuse this while printing the symbol list of the `sv.verbatim` op)

In general I'm quite happy if an attribute is a declared operand to print it however the op wants.

2022-05-25 20:33 UTC, darthscsi approved these changes
Much nicer looking.

2022-05-25 23:39 UTC, merged

2022-05-26 00:18 UTC, seldridge commented
This is a fantastic improvement. Thanks for doing this. 💯 

Target syntax would be nice. I have biases because I'm used to it, though. Nevertheless, this patch is strictly better than it was before. Nice work.

2022-05-26 00:59 UTC, youngar commented
> Target syntax would be nice.

It's what I wanted at first, but I disliked how it would be slightly different from a how "target string" is formatted.  An example NLA `[@Foo::@bar, @Bar::@b]` would be printed as `Foo/bar:Bar/b`. The closest equivalent target string would be `Foo/bar:Bar/b:B` or `Foo/bar:Bar>b`.  Maybe that isn't that bad?

2022-05-26 01:19 UTC, darthscsi commented
I strongly prefer something that isn't as hard to decode as the firrtl
target string stuff and isn't trying to evolve from an instance is module
confusion.  '::' matches mlir nested symbols which is a plus.

On Wed, May 25, 2022 at 7:59 PM Andrew Young ***@***.***>
wrote:

> Target syntax would be nice.
>
> It's what I wanted at first, but I disliked how it would be slightly
> different from a how "target string" is formatted. An example NLA
> ***@***.******@***.***, @***@***.*** would be printed as Foo/bar:Bar/b. The closest
> equivalent target string would be Foo/bar:Bar/b:B or Foo/bar:Bar>b. Maybe
> that isn't that bad?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/llvm/circt/pull/3179#issuecomment-1138028103>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACY5KK6QNV4FCMU5FYN5UATVL3EGHANCNFSM5WYNKD2A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-26 02:04 UTC, seldridge commented
If we went with target syntax, it should be the same as SFC targets, i.e., `Foo/bar:Bar>b` and not `Foo/bar:Bar/b`. The current approach of `[@Foo::@bar, @Bar::@bar]` is totally fine and does align better with MLIR conventions (and shows symbol usage obviously) as opposed to forcing SFC-style syntax for no clear benefit.