[MSFT] Factor out Quartus/Stratix10 logic from TclEmitter
llvm/circt pull request #3640
Opened 2022-08-01 13:54 UTC by mortbopet

Refactoring commit which makes `TclEmitter` generic by allowing inheriting classes to provide custom `TclOutputState` classes. Furthermore, adds new arguments to `msft-export-tcl` to select tcl flavor and target device, respectively.
The intention of this refactor is to facilitate writing TCL emitters for alternative flows and devices.

2022-08-03 20:57 UTC, teqdruid requested changes
The Quartus API won't (or is very unlikely to) change radically between families. If anything, it could change version-to-version! So please drop the S10 stuff. If we find it necessary to make small tweaks on a per-family basis (e.g. the DSPs in other families aren't called MPDSP), we should add special cases since 99% of the output is the same.

2022-08-03 20:57 UTC, teqdruid commented on include/circt/Dialect/MSFT/TclEmitter.h
> +  bool populated = false;
Setting `false` here is redundant with the constructor.

2022-08-03 20:57 UTC, teqdruid commented on include/circt/Dialect/MSFT/TclEmitter.h
> +  bool populated = false;
Can you move `topLevelSymbols` down as well. I'd like to keep these grouped.

2022-08-08 06:49 UTC, mortbopet commented on include/circt/Dialect/MSFT/TclEmitter.h
To me, a rename makes sense to reflect the class that's implemented in the file through the filename (`TclEmitter.h` implements `class TclEmitter`) - even more so, now that other files are expected to subclass `TclEmitter`.

2022-08-08 06:49 UTC, mortbopet commented on include/circt/Dialect/MSFT/MSFTPasses.td
> +    Option<"device", "device", "std::string",
Will drop device for now.

2022-08-08 16:17 UTC, teqdruid approved these changes
lgtm. thanks!

2022-08-08 16:17 UTC, teqdruid commented on lib/Dialect/MSFT/MSFTPasses.cpp
> +  if (tool == "quartus")
Please surround both blocks with curly brackets if one is necessary.

2022-08-31 11:36 UTC, closed without merging