[Comb] Introduce synopsys mux intrinsics
llvm/circt pull request #5427
Opened 2023-06-20 10:21 UTC by uenoku

This commit adds two target specific intrincis `comb.int.synopsys.{mux4, mux2}`, which directly represent 4-to-1 and 2-to-1 MUX cells in the synopys target.

To preserve the operation cleanly, new operations are added instaed of adding new attributes to mux.

PrepareForEmission lowers these operations into wire + assign + mux pragma.

2023-06-20 11:27 UTC, mortbopet commented
Has this been discussed at an ODM? We've been talking about device/target libraries for ages, so i'd hope more effort would go into that route, instead of encoding target-specific primitives as operations in the core dialect (for the obvious reason of introducing op bloat; this approach seems like a pandoras box).

2023-06-20 12:11 UTC, uenoku commented
Thanks, I should have brought up first in the ODM :pray: Let's talk in this week.  I'm totally fine with separating these operations into a new target specific dialect. I remember we have talked about hw.generic as well, but not sure we can use for this case.

2023-06-20 15:41 UTC, darthscsi requested changes
This should not be in comb.

Do we want a separate cadence and synopsys mux or do we want a "map to mux cell" mux?

2023-06-20 15:42 UTC, uenoku commented
> Do we want a separate cadence and synopsys mux or do we want a "map to mux cell" mux?

2023-06-21 19:01 UTC, uenoku commented
Based on the discussion, I'll just use SV attributes directly.

2023-06-21 19:01 UTC, closed without merging