[firtool] Add option to disable black box resource
llvm/circt pull request #6650
Opened 2024-02-06 08:35 UTC by unlsycn

Add the `--disable-blackbox-resource-file` option to firtool and the BlackBoxReaderPass.

Fix #4249. Another way to resolve it is adding an optional output filename for this file, but this would break the uniformity of the behavior when split-verilog is turn on or off.

Note that this option also works for targets other than verilog/systemverilog.

This switch does not affect the workflows that exists.

2024-02-06 10:08 UTC, SpriteOvO reviewed
Thanks for your first-time contribution! 👍 I left some comments, and please add some tests for this new option so that we can make sure that everything works fine with it enabled as well.

2024-02-06 13:51 UTC, unlsycn commented on lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp
> +                                     /*excludeFromFileList=*/true));
The semantics of hte option itself is to not generate this file. And it's disabled by default hence i don't think it will impact on existing flows.

2024-02-06 14:31 UTC, SpriteOvO commented on include/circt-c/Firtool/Firtool.h
> +    CirctFirtoolFirtoolOptions options, bool value);
This function also needs a definition in `lib/CAPI/Firtool/Firtool.cpp`. Other than this looks good to me.

2024-02-12 16:31 UTC, darthscsi requested changes
This is patching around the issue rather than fixing it.  The issue is that export verilog is adding a file list when it shouldn't because the modules exist in the verbatim.  The solution is not to drop the files form the flow.

2024-02-26 13:47 UTC, closed without merging

2024-02-27 07:34 UTC, unlsycn commented
> This is patching around the issue rather than fixing it. The issue is that export verilog is adding a file list when it shouldn't because the modules exist in the verbatim. The solution is not to drop the files form the flow.

So why do we need a file list for blackboxes? The pass get inlineText from all blackbox annotations and add them to the verbatim, so in the current case if we remove the files which in the verbatim from the file list, there must be nothing left of it.