[NFC][SV] Remove unnecessary dependency of SV on Verif
llvm/circt pull request #7249
Opened 2024-06-27 21:13 UTC by TaoBi22

Same situation as #7247, SV depends on Verif but that seems to be unnecessary as long as om-linker and HWToBTOR2 CMakeLists are updated to link in Verif

2024-06-27 21:29 UTC, dtzSiFive approved these changes
LGTM.

In ODS, SV is marked as depending on HW and Comb, which matches what we link in after this PR.

(Having these two aligned seems like a good rule of thumb)

2024-06-27 21:30 UTC, dtzSiFive requested changes
Hold on, SVPasses.td mentions that extract-test-code depends on Verif.

2024-06-27 21:34 UTC, dtzSiFive commented
Sorry for the back-and-forth!

Looks like we do link the Verif dialect into SVTransforms, so maybe this is good to go.  Going to circle back (and maybe others take a look/have thoughts).

Thanks for pushing on this! :+1:.

2024-06-27 21:43 UTC, TaoBi22 commented
> Sorry for the back-and-forth!
> 
> Looks like we do link the Verif dialect into SVTransforms, so maybe this is good to go. Going to circle back (and maybe others take a look/have thoughts).
> 
> Thanks for pushing on this! 👍.

No worries, thanks for taking a look! Strictly only one of this and #7247 is needed to break the cycle I need to break (so I can have Verif depend on Seq), just figured it was worth tidying them both up while I was at it (although #7247 has the same case with a LowerSeqHLMem dep on SV that's linked for CIRCTSeqTransforms).

2024-06-28 07:11 UTC, maerhart commented
> Looks like we do link the Verif dialect into SVTransforms, so maybe this is good to go. 

I agree with this analysis. Linking the transform/conversion libraries against Verif should be enough since the dialect library does not seem to use anything from Verif. Thus, the dependency of `CIRCTSV` on `CIRCTVerif` can go.

2024-06-28 13:44 UTC, dtzSiFive commented on tools/om-linker/CMakeLists.txt
> +  CIRCTVerif
This makes sense, the om-linker itself is what needs the Verif dialect.  Thanks!

2024-06-28 13:45 UTC, dtzSiFive approved these changes
LGTM, thanks!

2024-06-28 13:48 UTC, TaoBi22 commented
Thanks again for looking into this @dtzSiFive!

2024-06-28 13:48 UTC, merged