[FIRRTL] Convert FModule passes to FModuleLike interface passes
llvm/circt pull request #7402
Opened 2024-07-30 01:30 UTC by dobios

This PR is derived from  #7374 and replaces all FModuleOp passes with FModuleLike interface passes, allowing for arbitrary hardware to exist outside of modules.

2024-07-30 15:14 UTC, darthscsi commented on lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp
> +      .Case<FModuleOp, FExtModuleOp, FIntModuleOp, FMemModuleOp, ClassOp,
The copy-and-pasting of this block is increasing the ops being visited by a lot of passes.  Very few passes deal with FExtModuleOp, for example, as they don't have bodies.

2024-07-30 15:15 UTC, darthscsi commented on lib/Dialect/FIRRTL/Transforms/EliminateWires.cpp
> +      .Case<FModuleOp, FExtModuleOp, FIntModuleOp, FMemModuleOp, ClassOp,
Do all these have wires in them?

2024-07-30 15:18 UTC, darthscsi requested changes
FModuleLike doesn't mean "has logic in it".  Filtering ops later (and less efficiently) in the runtime may exacerbate parallel task balance issues.  Assuming a new top-level op which can contain logic makes sense (I haven't looked at that), the way to deal with it is not to make passes operate on FModuleLike.  (I also have looked to see if the new construct should even be FModuleLike.  Can it be instantiated with instance ops?)

2024-08-09 18:16 UTC, dobios commented
This is no longer needed since the FormalOp redesign.

2024-08-09 18:16 UTC, closed without merging