[FIRRTL] Add parser-timing firtool option
llvm/circt pull request #816
Opened 2021-03-24 13:18 UTC by fabianschuiki

Add the `--parser-timing` option to firtool. If present, the time taken to parse the FIRRTL or MLIR input is emitted alongside any other potential statistics. Fixes #608.

For example, `firtool test/ExportVerilog/rtl-dialect.mlir -verilog --pass-timing --parser-timing` produces the following output:
```
  MLIR Parser Execution Time: 0.0135 seconds

===-------------------------------------------------------------------------===
                      ... Pass execution timing report ...
===-------------------------------------------------------------------------===
  Total Execution Time: 0.0497 seconds

   ---User Time---   ---Wall Time---  --- Name ---
   0.0026 (  4.7%)     0.0026 (  5.1%)  LowerFIRRTLToRTL
   0.0055 ( 10.2%)     0.0011 (  2.2%)  'rtl.module' Pipeline
   0.0055 ( 10.2%)     0.0011 (  2.2%)    RTLCleanup
   0.0035 (  6.5%)     0.0035 (  7.1%)  CSE
   0.0001 (  0.2%)     0.0001 (  0.2%)    (A) DominanceInfo
   0.0425 ( 78.5%)     0.0425 ( 85.5%)  Canonicalizer
   0.0541 (100.0%)     0.0497 (100.0%)  Total
```

2021-03-24 19:23 UTC, darthscsi requested changes
The goal here, I think, is that parser timing be reported with existing --pass-timing option though the existing pass stat support.

2021-03-24 19:55 UTC, fabianschuiki commented
> Why the separate pass option? The goal is to output with pass-timing using the existing pass timing infrastructure. Likewise, doesn't mlir have timing helpers already?

@darthscsi That was also my first reflex. But most of the pass timing infrastructure of MLIR is private and hidden away. There's mainly the [`PassTiming` business](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Pass/PassTiming.cpp), which exposes itself as a `PassInstrumentation` and handles all the printing. Unfortunately there is only very little public API exposed there.

I initially thought that we could somehow seek out the `PassTiming` instrumentation from the `PassManager`'s list of instrumentors, but there's no public API for that I think. Alternatively, we could actually move the parser into a separate pass, but I don't see how that would work without a few nasty hacks (since the `PassManager` wants to run on an operation).

We could also push for some additions to the public API in MLIR upstream.

2021-03-24 21:00 UTC, lattner commented
I'd also prefer for this to be integrated with the pass timing stuff.

> We could also push for some additions to the public API in MLIR upstream.

I suspect the MLIR upstream folks would be happy to improve this.  Could you start a thread on the MLIR forum to discuss it?

2021-03-24 21:07 UTC, lattner commented
btw, thank you for tackling this!  Another wishlist that I'd love to see is an "end to end time", which would be a total (or delta) of otherwise-unaccounted for time.

2021-03-25 12:21 UTC, fabianschuiki commented
I [added a topic on the MLIR discourse](https://llvm.discourse.group/t/ways-to-add-entries-to-pass-timing-from-outside-the-passmanager/3115) that describes what we're trying to do. Could be nice to have `PassTiming` and `Timer` be public for one, and to have them be user-providable to the pass manager such that we can measure additional stuff surrounding the pass manager itself.

2021-03-25 17:45 UTC, lattner commented
nice, thanks!

2021-03-29 13:32 UTC, fabianschuiki commented
It would probably make sense to come up with a concrete suggestion for changes upstream. I can whip something up to have a better basis for discussion.

2021-04-16 14:23 UTC, fabianschuiki commented
Submitted [a patch](https://reviews.llvm.org/D100647) upstream that gets firtool to produce the following with `--pass-timing`:
```
===-------------------------------------------------------------------------===
                      ... Pass execution timing report ...
===-------------------------------------------------------------------------===
  Total Execution Time: 27.2735 seconds

   ---User Time---   ---Wall Time---  --- Name ---
  11.6806 ( 39.0%)    11.6806 ( 42.8%)  Parser
   8.8685 ( 29.6%)     8.8685 ( 32.5%)  'firrtl.circuit' Pipeline
   4.9709 ( 16.6%)     4.9709 ( 18.2%)    LowerFIRRTLTypes
   3.8976 ( 13.0%)     3.8976 ( 14.3%)    'firrtl.module' Pipeline
   1.9258 (  6.4%)     1.9258 (  7.1%)      CSE
   0.0149 (  0.0%)     0.0149 (  0.1%)        (A) DominanceInfo
   1.9718 (  6.6%)     1.9718 (  7.2%)      Canonicalizer
   1.9416 (  6.5%)     1.9416 (  7.1%)  LowerFIRRTLToRTL
   0.4313 (  1.4%)     0.4313 (  1.6%)  RTLMemSimImpl
   3.9942 ( 13.3%)     1.3273 (  4.9%)  'rtl.module' Pipeline
   0.8511 (  2.8%)     0.2973 (  1.1%)    RTLCleanup
   0.9278 (  3.1%)     0.3027 (  1.1%)    CSE
   0.0397 (  0.1%)     0.0149 (  0.1%)      (A) DominanceInfo
   2.2153 (  7.4%)     0.7273 (  2.7%)    Canonicalizer
   0.4037 (  1.3%)     0.4037 (  1.5%)  RTLLegalizeNames
   0.0497 (  0.2%)     0.0497 (  0.2%)    (A) circt::sv::LegalNamesAnalysis
   2.6205 (  8.8%)     2.6205 (  9.6%)  Output
  29.9403 (100.0%)    27.2735 (100.0%)  Total
```
I'll update this PR as the upstreaming progresses.

2021-04-17 17:10 UTC, lattner commented
awesome, thank you for driving this forward @fabianschuiki !

2021-05-07 05:43 UTC, lattner commented
great work Fabian, I'm really looking forward to this!

2021-05-12 17:26 UTC, lattner approved these changes

2021-05-12 19:05 UTC, merged